project/board/urls.py
from django.urls import path
from .views import IndexView, NewOrderView, take_order

urlpatterns = [
    path('', IndexView.as_view()),
    path('new/', NewOrderView.as_view(), name = 'new_order'),
    path('take/<int:oid>', take_order, name = 'take_order')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('portal.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('portal/', include('portal.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path("accounts/", include("accounts.urls")),
]

project/portal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.cache import cache




class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.SmallIntegerField("рейтинг автора", default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.authorRating = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser.username}'


class Category(models.Model):
    categoryName = models.CharField('Выберите категорию публикаций для подписки:', max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories', blank=True, null= True)
    
    def __str__(self):
        return f'{self.categoryName}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'Новость'
    ARTICLE = 'Статья'
    CATEGORIES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    ]
    categoryType = models.CharField(max_length=10,
                                     choices=CATEGORIES,
                                     default=ARTICLE)
    
    category = models.ManyToManyField(Category, through='PostCategory')

    publicationDate = models.DateTimeField('Publication date ', auto_now_add=True)
    postTitle = models.CharField('Title ', max_length=128)
    postContent = models.TextField('Content')
    rating = models.SmallIntegerField("рейтинг статьи/новости", default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{self.postContent[:124]} ...'

    def __str__(self):
        return f'{self.postTitle}. {self.postContent[:124]} ...'

    def get_absolute_url(self):
        return f'http://127.0.0.1:8000/portal/{self.id}'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'Post-{self.pk}')

    def message_subscriber(self):
        return f'Новая статья - "{self.postTitle}" в разделе "{self.category.first()}" '


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post}. {self.category}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    commentText = models.CharField('текст комментария', max_length=200)
    publicationDate = models.DateTimeField('дата и время публикации комментария', auto_now_add=True)
    rating = models.SmallIntegerField("рейтинг комментария", default=0)

    def __str__(self):
        return f'{self.commentUser.username}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def postComment(self):
        return f'Комментарий к статье:\n Дата: {self.publicationDate}\nПользователь: {self.commentUser}\n Рейтинг: {self.rating}\n Коментарий: {self.commentText}'

project/templates/post/post_create.html
<! -- наследование шаблона default -->
{% extends 'flatpages/default.html' %}

{% block title %} Create The Post {% endblock title %}

{% block content %}
<h3>Информация о статье</h3>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Запостить!">
</form>

<br>
<button> <a class="nav-link" href="/portal/">Вернуться</a> </button>


{% endblock content %}

project/templates/post/post_delete.html
<! -- наследование шаблона default -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block content %}
<h2>Вы действительно хотите удалить данную статью?</h2>
<table>
    <tr>
        <td>
            <b>
                № &nbsp
            </b>
        </td>
        
        <td>
            <b>
                &nbsp Заголовок 
            </b>
        </td>

        <td>
            <b>
                 &nbsp &nbsp Текст 
            </b>
        </td>

        <td>
            <b>
                &nbsp &nbsp Категория &nbsp
            </b>
        </td>

        <td>
            <b>
                &nbsp &nbsp &nbsp  Тип поста &nbsp
            </b>
        </td>

        <td>
            <b>
                &nbsp &nbsp &nbsp Дата публикации &nbsp
            </b>
        </td>
    </tr>

    <tr>
        <td>
            {{ post.id }}
        </td>

        <td>
            &nbsp {{ post.postTitle|default:"Без заголовка"|truncatewords:3|censor}}
        </td>
        <td>
            &nbsp &nbsp   {{ post.postContent|truncatechars:50|censor}}
        </td>
        

        <td> 
            {{ category }}
        </td>
        <td> 
            &nbsp &nbsp &nbsp {{ post.categoryType }}
        </td>
        <td>
            &nbsp &nbsp &nbsp {{ post.publicationDate|default:"Без даты" }}
        </td>
    </tr>
</table>

<hr>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>

    <br>
<button> <a class="nav-link" href="/portal/">Вернуться</a> </button>
{% endblock content %} 

project/templates/post/post_details.html
{% extends 'flatpages/default.html' %}
 
{% block title %} Post detail {% endblock title %}
{% load custom_filters %}
{% block content %}

<table>
    <tr>
        <td>
            <b>
                № 
            </b>
        </td>
        
        <td>
            <b>
                &nbsp &nbsp Заголовок 
            </b>
        </td>

        <td>
            <b>
                  Текст 
            </b>
        </td>

        <td>
            <b>
                &nbsp Категория 
            </b>
        </td>
        <td>
            <b>
                Тип  &nbsp &nbsp &nbspпоста 
            </b>
        </td>

        <td>
            <b>
                Дата публикации 
            </b>
        </td>
    </tr>

    <tr>
        <td>
            {{ post.id }}
        </td>

        <td>
            {{ post.postTitle|default:"Без заголовка"|censor}}
        </td>
        <td>
            {{ post.postContent|censor }}
        </td>
        <td> 
            {{ category }}
        </td>
        <td>
            {{ post.categoryType}}
        </td>
        <td>
            {{ post.publicationDate|default:"Без даты" }}
        </td>
        <td>
            {% if perms.portal.change_post %}
            <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
            {% endif %}
            {% if perms.portal.delete_post %}
            <a href="{% url 'post_delete' post.id %}">Удалить</a>
            {% endif %}
            </td>
    </tr>
</table>

<br>
<button> <a class="nav-link" href="/portal/">Вернуться</a> </button>

{% endblock content %}

project/templates/post/post_list.html
<! -- наследование шаблона default -->
{% extends 'flatpages/default.html' %}

{% block title %} News {% endblock title %}

{% load custom_filters %}

<! -- начало контента -->
{% block content %}



<h1>Новости</h1>
<hr>

{% if post_list %}
    <table>
        <tr>
            <td>
                <b>
                    № &nbsp
                </b>
            </td>
            
            <td>
                <b>
                    Заголовок 
                </b>
            </td>

            <td>
                <b>
                     &nbsp &nbsp Текст 
                </b>
            </td>

            <td>
                <b>
                    Категория &nbsp
                </b>
            </td>
            <td>
                <b>
                    &nbsp &nbsp &nbsp  Тип поста &nbsp
                </b>
            </td>
            <td>
                <b>
                    &nbsp &nbsp &nbsp &nbsp  Дата публикации 
                </b>
            </td>
        </tr>
        {% for post in post_list %}
        <tr>
            <td>
                {{ post.id }}
            </td>

            <td>
                <!-- гиперсслыка -->
                <a href="{% url 'post_detail' post.id %}"> {{ post.postTitle|default:"Без заголовка"|truncatewords:3|censor}}
            <br>
            </td>
            
            <td>
                &nbsp &nbsp {{ post.postContent|truncatechars:50|censor}}
            </td>
            <td> 
                
            </td>
            <td>
                &nbsp &nbsp &nbsp  {{ post.categoryType }}
            </td>
            <td>
                &nbsp &nbsp &nbsp &nbsp {{ post.publicationDate|default:"Без даты" }}
            </td>
            <td>
                {% if perms.portal.change_post %}
                <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
                {% endif %}
                {% if perms.portal.delete_post %}
                <a href="{% url 'post_delete' post.id %}">Удалить</a>
                {% endif %}
                </td>
        {% endfor %}
        
        </tr>
    </table>
{% else %}
<h2>
    Новостей нет!
</h2>
{% endif %}

<br>

<!-- блок пагинатора -->

{% if is_paginated %} 
   
    {% if page_obj.has_previous %}
        <a href="?page=1">Первая стр.</a>
        <a href="?page={{ page_obj.previous_page_number }}"><</a>
        <div class="col-lg-12 text-center"></div>   
    {% endif %}
 
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
 
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя стр.</a>
    {% endif %}
 
{% endif %}





{% endblock content %}

project/templates/post/post_search.html
<! -- наследование шаблона default -->
{% extends 'flatpages/default.html' %}

{% block title %} Find News {% endblock title %}

{% load custom_filters %}



<! -- начало контента -->
{% block content %}

<h1>Новости</h1>

<hr>

<!-- Перед таблицей добавим форму для поиска -->
<form method="GET">
    {{ search.form }} <!-- Форму от фильтров за нас сделает django.
    А вот кнопку, увы придётся делать самому -->
    <input type="submit" value="Найти">
</form>

<hr>

{% if search.qs %}

<table>
	<tr>
		<td>
			<b>
				№ &nbsp
			</b>
		</td>
		
		<td>
			<b>
				&nbsp Заголовок 
			</b>
		</td>

		<td>
			<b>
				 &nbsp &nbsp Текст 
			</b>
		</td>

		<td>
			<b>
				&nbsp &nbsp Категория &nbsp
			</b>
		</td>
        <td>
            <b>
                &nbsp &nbsp &nbsp  Тип поста &nbsp
            </b>
        </td>

		<td>
			<b>
				&nbsp &nbsp &nbsp Дата публикации &nbsp
			</b>
		</td>
	</tr>
		{% for post in search.qs %}
		<tr>
            <td>
                {{ post.id }}
            </td>

            <td> &nbsp
                <!-- гиперсслыка -->
                <a href="{% url 'post_detail' post.id %}"> {{ post.postTitle|default:"Без заголовка"|truncatewords:3|censor}}
            <br>
            </td>
            <td>
                &nbsp &nbsp {{ post.postContent|truncatechars:50|censor}}
            </td>
            <td> 
                {{ category }}
            </td>
            <td> 
                &nbsp &nbsp &nbsp {{ post.categoryType}}
            </td>
            <td>
                &nbsp &nbsp &nbsp {{ post.publicationDate|default:"Без даты" }}
            </td>
		{% endfor %}
		</tr>
	</table>
{% else %}
<h2>
    Новостей нет!
</h2>
{% endif %}


<br>

<!-- блок пагинатора -->


{% if is_paginated %} 
   
    {% if page_obj.has_previous %}
        <a href="?page=1">Первая стр.</a>
        <a href="?page={{ page_obj.previous_page_number }}"><</a>
        <div class="col-lg-12 text-center"></div>   
    {% endif %}
 
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
 
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя стр.</a>
    {% endif %}

{% endif %}


<br>
<button> <a class="nav-link" href="/portal/">Вернуться</a> </button>


<! -- конец контента -->
{% endblock content %}

project/templates/post/post_update.html
{% extends 'flatpages/default.html' %}
 
{% block title %} News Portal {% endblock title %}
 
{% block content %}
<h3>Редактирование поста</h3>
<form method="POST">
    {% csrf_token %} 
    {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Редактировать пост">
</form>

<br>
<button> <a class="nav-link" href="/portal/">Вернуться</a> </button>

{% endblock content %}